dobby/config/routes.rb
Dobby::Application.routes.draw do
  devise_for :users do
    get "/", :to => "devise/sessions#new"
  end

  resources :users, :only => :show
  resources :weeks, :only => [:index, :edit, :update]
  resources :games, :only => [:index, :edit, :update]
  resources :admin, :only => :index
  root :to => "devise/sessions#new"
  
end

dobby/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    if user.admin?
      can :manage, :all
    end
    if user.admin == false
      can :manage, UsersPick
      can :read, Week
      can :manage, Game
    end 
  end
end

dobby/app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :away_team, :class_name => Team.new
  belongs_to :home_team, :class_name => Team.new
  belongs_to :week
  has_many :users_picks, :order => "index DESC"
end

dobby/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :games
end

dobby/app/models/user.rb
class User < ActiveRecord::Base
  has_many :users_picks
  has_many :users_lines
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :lastName, :firstName
  
  def admin?
    self.admin == true rescue false
  end
end

dobby/app/models/users_pick.rb
class UsersPick < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  belongs_to :week
end

dobby/app/models/week.rb
class Week < ActiveRecord::Base
  has_many :games
  has_many :users_picks
  has_many :users_lines
  accepts_nested_attributes_for :games, :allow_destroy => true 
  
  validate :saved_games_unique
  
  def saved_games_unique
    teams = []
    valid = true
    self.games.each do |game|
      if game.away_team_id != nil && game.home_team_id
	if teams.include?(game.away_team_id)
	  valid = false
	  game.errors.add(:away_team_id, 'is already used')
	else
	  teams << game.away_team_id
	end
	if teams.include?(game.home_team_id)
	  valid = false
	  game.errors.add(:home_team_id, 'is already used')
	else
	  teams << game.home_team_id 
	end
      end
    end
    p teams
    if valid == false
      self.errors.add(:base, "Duplicate team saved.")
    end
  end
       
end

dobby/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  authorize_resource :class => false
end

dobby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  
  protected
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end 
  
  def get_current_season
    @get_current_season = 1
  end
  
  def get_week
    week = Week.where("year = #{get_current_year}").last
    if week.nil?
      @get_week = 1
    else
      @get_week = week.week + 1
    end
  end
  
  def get_current_week
    @get_current_week = 1
  end
  
  def get_current_year
    @get_current_year = 2012
  end
end

dobby/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :get_current_year, :get_current_week
  load_and_authorize_resource
  
  def index
    @weeks = Week.where("year = '#{@get_current_year}'")
  end
  
  def edit
    @week = Week.find(params[:id])
    @games = @week.games
    @users_picks = UsersPick.where("user_id = #{current_user.id} AND week_id = #{params[:id]}").first
  end
  
  def update
    @users_picks = UsersPick.where("user_id = #{current_user.id} AND week_id = #{params[:id]}").first
    if @users_picks.nil?
      @users_picks = current_user.users_picks.build(params[:users_picks])
      @users_picks.week_id = params[:id]
      if @users_picks.save
       redirect_to edit_game_path(params[:id])
      else
	render 'edit'
      end
    else
      if @users_picks.update_attributes(params[:users_picks])
	redirect_to edit_game_path(params[:id])
      else
	render 'edit'
      end
    end
  end
end

dobby/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(current_user.id)
  end
end

dobby/app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_filter :get_current_year
  load_and_authorize_resource
  
  def index
    @weeks = Week.where("year = '#{@get_current_year}'")
    if @weeks == [] || @weeks.nil?
      @weeks = Array.new(17) { Week.new(:year => @get_current_year) }
      @weeks.each_with_index do |week, index|
	week.week = index + 1
      end
      @weeks.each(&:save!)
    end
  end
  
  def edit 
    @teams = Team.find(:all, :order => "Name ASC")
    if !@week.games.present?
      16.times { @week.games.build }
      @week.games.each_with_index do |game, index|
	game.index = index + 1
      end
      @week.games.each(&:save!)
    end
  end
  
  def update
    @teams = Team.find(:all, :order => "Name ASC")
    @week = Week.find(params[:id])
    if @week.update_attributes(params[:week])
      redirect_to edit_week_path(params[:id])
    else
      render 'edit'
    end
  end
end

dobby/app/helpers/admin_helper.rb
module AdminHelper
end

dobby/app/helpers/application_helper.rb
module ApplicationHelper
end

dobby/app/helpers/games_helper.rb
module GamesHelper
  def get_team_name(teamNumber)
    team = Team.find(teamNumber)
    team.name
  end 
  
  def disable_submit?
    week = Week.find(@game.week_id)
    if week.week != @get_current_week
      false
    else
      true
    end
  end
end

dobby/app/helpers/week_helper.rb
module WeekHelper
end

dobby/app/helpers/weeks_helper.rb
module WeeksHelper
end

dobby/app/views/admin/index.html.erb
<h1> Admin Index </h1>
<%= link_to "Create Games", weeks_path %>
<div class="navigation-links">
  <%= link_to "User Index", user_path(current_user) %>
</div>

dobby/app/views/games/edit.html.erb
<h1> Week <%= @games[0].index %> Games </h1>
<%= form_for :users_picks, :url => game_path(params[:id]), :method => :put do |f| %>
  <table>
    <tr>
      <th class="game_header"> Away </th>
      <th></th>
      <th class="game_header home_team_label"> Home </th>
      <th class="game_header spread_column"> Spread </th>
    </tr>
    <% @games.each_with_index do |game, index| %>
      <tr>
	<% if game.away_team_id.present? && game.home_team_id.present? %>
	  <% if @users_picks != [] && @users_picks.present? %>
	    <% if @users_picks.send("game#{index + 1}") != nil %>
	      <% if game.away_team_id == @users_picks.send("game#{game.index}") %>
		<td><%= f.radio_button("game#{game.index}", game.away_team_id, :checked => true) %> <%= label_tag("users_picks'game#{game.id}'#{game.away_team_id}", get_team_name(game.away_team_id)) %></td> 
		<td class="vs-label">vs. </td>
		<td class="home_team_label"><%= f.radio_button("game#{game.index}", game.home_team_id) %> <%= label_tag("users_picks'game#{game.id}'#{game.home_team_id}", get_team_name(game.home_team_id)) %> <br/></td>
	      <% else %>
		<td><%= f.radio_button("game#{game.index}", game.away_team_id) %> <%= label_tag("users_picks'game#{game.id}'#{game.away_team_id}", get_team_name(game.away_team_id)) %></td> 
		<td class="vs-label">vs.</td> 
		<td class="home_team_label"><%= f.radio_button("game#{game.index}", game.home_team_id, :checked => true) %> <%= label_tag("users_picks'game#{game.id}'#{game.home_team_id}", get_team_name(game.home_team_id)) %> <br/></td>
	      <% end %>
	    <% else %>
	      <td><%= f.radio_button("game#{game.index}", game.away_team_id) %> <%= label_tag("users_picks'game#{game.id}'#{game.away_team_id}", get_team_name(game.away_team_id)) %> </td>
	      <td class="vs-label">vs. </td>
	      <td class="home_team_label"><%= f.radio_button("game#{game.index}", game.home_team_id) %> <%= label_tag("users_picks'game#{game.id}'#{game.home_team_id}", get_team_name(game.home_team_id)) %> <br/></td>
	    <% end %>
	  <% else %>
	    <td><%= f.radio_button("game#{game.index}", game.away_team_id) %> <%= label_tag("users_picks'game#{game.id}'#{game.away_team_id}", get_team_name(game.away_team_id)) %> </td>
	    <td class="vs-label">vs. </td>
	    <td class="home_team_label"><%= f.radio_button("game#{game.index}", game.home_team_id) %> <%= label_tag("users_picks'game#{game.id}'#{game.home_team_id}", get_team_name(game.home_team_id)) %> <br/></td>
	  <% end %>
	<% end %>
	<td class="spread_column"><%= game.spread %></td>
      </tr>
    <% end %>
  </table>
  <div class="actions navigation-links">
    <% if disable_submit? %>
      <%= f.submit %> |
    <% end %> 
    <% p disable_submit? %>
    <%= link_to "Games Index", games_path %> | <%= link_to "User Index", user_path(current_user) %>
  </div>
<% end %>

dobby/app/views/games/index.html.erb
<h1> Weeks </h1>
<% @weeks.each do |week| %>
  <% if week.week <= @get_current_week %>
    <%= link_to "Week #{week.week}", edit_game_path(week.id) %><br/>
  <% else %>
    <%= link_to "Week #{week.week}", edit_game_path(week.id), :class => 'disable_link' %><br/>
  <% end %>
<% end %>
<br/>
<div class="navigation-links">
  <%= link_to "User Index", user_path(current_user) %>
</div>

dobby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dobby</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_tag "$.datepicker.setDefaults({ buttonImage: '#{image_path 'calendar.png'}'})" %>
</head>
<body>
  <div id="container">
    <div id="container-contents">
      <div id="user_nav">
	<% if user_signed_in? %>
	  Signed in as <%= current_user.email %>. Not you?
	  <%= link_to "Sign out", destroy_user_session_path %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
	<% end %>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
</html>

dobby/app/views/users/show.html.erb
<h1> <%= @user.firstName %>'s Page </h1>


<%= link_to "Pick'em", games_path %><br/>
<%= link_to "Lines", users_lines_path %><br/>
<% if current_user.admin == true %>
  <%= link_to "Admin Page", admin_index_path %>
<% end %>

dobby/app/views/weeks/_game_fields.html.erb
<tr>
  <td><%= f2.label :game, "Game #{f2.object.index}", :class => 'game_label' %></td>

  <td><%= f2.select :away_team_id, options_from_collection_for_select(@teams, :id, :name, f2.object.away_team_id), {:include_blank => 'Please Select'}%></td> 
    
  <td>vs.</td>

  <td><%= f2.select :home_team_id, options_from_collection_for_select(@teams, :id, :name, f2.object.home_team_id), {:include_blank => 'Please Select'}%></td>

  <td><%= f2.text_field :date, :class => 'datepicker' %></td>

  <td><%= f2.text_field :time, :class => 'timepicker' %></td>

  <td><%= f2.text_field :spread, :class => 'spread_field' %></td>
</tr>

dobby/app/views/weeks/edit.html.erb
<h1> Create Games </h1>
<%= form_for @week do |f|%>
  <%= f.error_messages %>
  <table>
    <%= f.fields_for :games do |f2| %>
      <%= render "game_fields", :f2 => f2%>
    <% end %>
  </table>
  <p><%= submit_tag "Submit" %> | <%= link_to "Week Index", weeks_path  %> </p>
<% end %>

dobby/app/views/weeks/index.html.erb
<h1> Weeks </h1>
<% @weeks.each do |week| %>
  <%= link_to "Week #{week.week}", edit_week_path(week.id) %><br/>
<% end %>
<br/>
<div class="navigation-links">
  <%= link_to 'User Index', user_path(current_user) %>
</div>

dobby/app/views/weeks/show.html.erb
<h1> Week <%= @week.week %> Games </h1>
<%= form_for :users_picks, :url => week_path(params[:id]), :method => "put" do |f| %>
  <table id='week-picks'>
  <% @week.games.each do |game, index| %>
    <% if @users_picks != [] && @users_picks.present? && @users_picks.send("game#{index}").present? %>
      <% if game.away_team_id == @users_picks.send("game#{game.index}") %>
	<tr>
	<td><%= f.radio_button("game#{game.index}", game.away_team_id, :checked => true) %> <%= label_tag("users_picks_game#{game.id}'#{game.away_team_id}", get_team_name(game.away_team_id))%></td>
	<td><%= label_tag :users_picks, "vs.", :class => 'vs_label' %></td>
	<td><%= f.radio_button("game#{game.index}", game.home_team_id, :class => 'home-team-radio-button') %> <%= label_tag("users_picks_game#{game.id}'#{game.home_team_id}", get_team_name(game.home_team_id)) %></td>
	<td class='spread'><%= game.spread %></td>
	</tr>
      <% else %>
	<tr>
	<td><%= f.radio_button("game#{game.index}", game.away_team_id) %> <%= label_tag("users_picks_game#{game.id}'#{game.away_team_id}", get_team_name(game.away_team_id)) %></td> 
	<td><%= label_tag :users_picks, "vs.", :class => 'vs_label' %></td>
	<td><%= f.radio_button("game#{game.index}", game.home_team_id, :checked => true, :class => 'home-team-radio-button') %> <%= label_tag("users_picks_game#{game.id}'#{game.home_team_id}", get_team_name(game.home_team_id)) %></td>
	<td class='spread'><%= game.spread %></td>
	</tr>
      <% end %>
    <% else %>
      <tr>
      <td><%= f.radio_button("game#{game.index}", game.away_team_id) %> <%= label_tag("users_picks_game#{game.id}'#{game.away_team_id}", get_team_name(game.away_team_id)) %></td>
      <td class='vs-label'><%= label_tag :users_picks, "vs." %> </td>
      <td class='home-team-radio-button'><%= f.radio_button("game#{game.index}", game.home_team_id) %> <%= label_tag("users_picks_game#{game.id}'#{game.home_team_id}", get_team_name(game.home_team_id)) %></td>
      <td class='spread'><%= game.spread %></td>
      </tr>
    <% end %>
  <% end %>
  </table>
  <div class="actions navigation-links">
    <%= f.submit %> | <%= link_to "User Index", user_path(current_user) %>
  </div>
<% end %>